[workspace]
members = [
    "num_printer",
    "num_printer/printer",
    "rng",
]

[workspace.dependencies]
num_printer = {path = "num_printer"}
printer = {path = "num_printer/printer"}
rng = {path = "rng"}

clap = "2.33.3"
ferris-says = "0.2.0"
