[package]
name = "fake_rules_rust_bindgen_lib"
version = "0.0.1"

[lib]
path = "fake_rules_rust_bindgen_lib.rs"

[dependencies]
bindgen = "0.54.0"
libloading = "=0.5.0"

[raze]
genmode = "Remote"
workspace_path = "//bindgen/raze"
gen_workspace_prefix = "rules_rust_bindgen"
output_buildfile_suffix = "BUILD"

[raze.crates.bindgen.'0.54.0']
gen_buildrs = true
extra_aliased_targets = ["cargo_bin_bindgen"]

[raze.crates.clang-sys.'0.29.3']
gen_buildrs = true

[raze.crates.libloading.'0.5.0']
additional_deps = [":global_static"]
additional_build_file = "libloading-global-static.BUILD"

[raze.crates.log.'0.4.11']
additional_flags = [
    "--cfg=atomic_cas",
]
