[raze]
genmode = "Remote"
workspace_path = "//wasm_bindgen/raze"

[raze.crates.wasm-bindgen-cli.'0.2.48']
gen_buildrs = true
extra_aliased_targets = ["cargo_bin_wasm_bindgen"]

[raze.crates.proc-macro2.'0.4.30']
additional_flags = [
    "--cfg=use_proc_macro",
]

[raze.crates.unicase.'1.4.2']
additional_flags = [
  "--cfg=__unicase__iter_cmp",
  "--cfg=__unicase__defauler_hasher",
]

[raze.crates.mime_guess.'1.8.7']
gen_buildrs = true

[dependencies]
wasm-bindgen-cli = "=0.2.48"
wasm-bindgen = "=0.2.48"

[raze.crates.rand_jitter.'0.1.4']
additional_deps = [
    "@raze__libc__0_2_58//:libc"
]

[raze.crates.syn.'0.15.43']
gen_buildrs = true
additional_flags = [
  "--cfg=syn_can_call_macro_by_path",
]

[raze.crates.libc.'0.2.58']
additional_flags = [
  "--cfg=libc_core_cvoid",
  "--cfg=libc_priv_mod_use",
  "--cfg=libc_union",
  "--cfg=libc_const_size_of",
  "--cfg=libc_align",
  "--cfg=libc_packagedN",
]

[raze.crates.openssl-sys.'0.9.47']
additional_flags = [
  # Vendored openssl is 1.0.2m
  "--cfg=ossl101",
  "--cfg=ossl102",
  "--cfg=ossl102f",
  "--cfg=ossl102h",
  "--cfg=ossl110",
  "--cfg=ossl110f",
  "--cfg=ossl110g",
  "--cfg=ossl111",
  "--cfg=ossl111b",
  "-l",
  "dylib=ssl",
  "-l",
  "dylib=crypto",
]

[raze.crates.backtrace.'0.3.32']
skipped_deps = [
    "backtrace-sys-0.1.29",
]
additional_deps = [
    "@wasm_bindgen_backtrace_sys_0_1_29//:backtrace_sys",
]

[package]
name = "fake_lib"
version = "0.0.1"

[lib]
path = "fake_lib.rs"
