default_stages: [pre-commit]
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude_types: [diff]  # don't touch patch files
      - id: trailing-whitespace
        exclude_types: [diff]  # don't touch patch files
  - repo: https://github.com/crate-ci/typos
    rev: v1.33.1
    hooks:
      - id: typos
        exclude: |
          (?x)^(
            cargo|
            crate_universe|
            examples|
            extensions|
            ffi|
            nix|
            rust|
            test|
            tools|
            util
          )
