[package]
name = "has_aliased_deps"
version = "0.1.0"
authors = ["Daniel Wagner-Hall <dwagnerhall@apple.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
