[package]
name = "rules_rust_examples_criterion_bench"
version = "0.0.1"
edition = "2018"

[dev-dependencies]
criterion = "0.3.5"

[lib]
name = "fake_criterion_lib"
path = "fake_criterion_lib.rs"

[package.metadata.raze]
workspace_path = "//benchmarking/criterion/raze"
genmode = "Remote"
gen_workspace_prefix = "rules_rust_examples_bench_criterion"
package_aliases_dir = "."

[package.metadata.raze.crates.bstr.'*']
data_attr = "glob([\"src/**\"])"

[package.metadata.raze.crates.criterion.'*']
data_attr = "glob([\"src/**\"])"
