"""An aspect for generating Cargo manifests (`Cargo.toml` files) for Rust targets.

cbindgen relies on `cargo metadata` to discover the source code of a crate and
its dependencies. Bazel does not require `Cargo.toml` files to exist for Rust
targets so this aspect synthesizes them for use with cbindgen.
"""

load("@rules_rust//rust:rust_common.bzl", "CrateInfo", "TestCrateInfo")

# Supported rule kinds for the cargo manifest aspect
_SUPPORTED_LIB_KINDS = ["rust_library", "rust_shared_library", "rust_static_library"]
_SUPPORTED_BIN_KINDS = ["rust_binary"]

CargoManifestInfo = provider(
    doc = "A provider containing information about a Crate's cargo metadata.",
    fields = {
        "deps": "The Cargo.toml files the current crate depends on.",
        "toml": "The current crate's Cargo.toml file.",
    },
)

def _path_parts(path):
    """Takes a path and returns a list of its parts with all "." elements removed.

    The main use case of this function is if one of the inputs to relativize()
    is a relative path, such as "./foo".

    Args:
        path (str): A string representing a unix path

    Returns:
        list: A list containing the path parts with all "." elements removed.
    """
    path_parts = path.split("/")
    return [part for part in path_parts if part != "."]

def _relativize(path, start):
    """Returns the relative path from start to path.

    Args:
        path (str): The path to relativize.
        start (str): The ancestor path against which to relativize.

    Returns:
        str: The portion of `path` that is relative to `start`.
    """
    src_parts = _path_parts(start)
    dest_parts = _path_parts(path)
    n = 0
    for src_part, dest_part in zip(src_parts, dest_parts):
        if src_part != dest_part:
            break
        n += 1

    relative_path = ""
    for _ in range(n, len(src_parts)):
        relative_path += "../"
    relative_path += "/".join(dest_parts[n:])

    return relative_path

def _output_dir(ctx):
    """Returns the output directory the aspect should write into.

    Args:
        ctx (ctx): The current aspect's context object

    Returns:
        string: The output directory name for the current aspect
    """
    return "cargo_manifest.aspect/{}".format(ctx.rule.attr.name)

def _is_external_crate(target):
    """Returns whether or not the target is an external target.

    Args:
        target (Target): The target the aspect is being applied to.

    Returns:
        bool: True if the target is an external target
    """
    return target.label.workspace_root.startswith("external")

def _find_crate_root_from_srcs(srcs):
    """Find the crate root file from a list of source files.

    Looks for `lib.rs` or `main.rs` as conventional entry points.

    Args:
        srcs (list): List of source files

    Returns:
        File: The crate root file, or None if not found
    """
    for src in srcs:
        if src.basename == "lib.rs" or src.basename == "main.rs":
            return src

    # Fallback to the first .rs file if no conventional root was found
    for src in srcs:
        if src.path.endswith(".rs"):
            return src
    return None

def _clone_external_sources(ctx, srcs, root):
    """Creates copies of the source files for external crates.

    This is done to ensure manifests generated for external targets can always
    refer to their source code via some predictable path.

    Args:
        ctx (ctx): The current aspect's context object
        srcs (list): List of source `File`s to clone
        root (File): The crate root within `srcs`.

    Returns:
        tuple: A tuple of the following items:
            - (list): A list of `File`s created by this macro
            - (File): The generated file matching the crate root.
    """
    outputs = []
    copy_commands = []
    output_root = None
    for src in srcs:
        external_crate_short_path = src.short_path.removeprefix("../")
        output = ctx.actions.declare_file("{}/{}".format(_output_dir(ctx), external_crate_short_path))
        outputs.append(output)
        copy_commands.append("mkdir -p {} ; cp {} {}".format(
            output.dirname,
            src.path,
            output.path,
        ))
        if root and src.path == root.path:
            output_root = output

    if outputs:
        ctx.actions.run_shell(
            outputs = outputs,
            inputs = srcs,
            command = "\n".join(copy_commands),
            mnemonic = "CargoManifestCloneSrcs",
        )

    return outputs, output_root

_CARGO_MANIFEST_TEMPLATE = """\
# Generated by `cargo_manifest_aspect` from `{target_label}` in `{build_file_path}`
[package]
name = "{name}"
version = "{version}"
edition = "{edition}"

{crate_type}
name = "{lib_name}"
path = "{path}"

[dependencies]
{dependencies}
"""

def _cargo_manifest_aspect_impl(target, ctx):
    """Creates a `Cargo.toml` for each instance of a Rust rule.

    Args:
        target (Target): The target the aspect is being applied to.
        ctx (ctx): The current aspect's context object

    Returns:
        list: A list of providers
            - (CargoManifestInfo): Information about the current target
            - (OutputGroupInfo): A provider that indicates what output groups a rule has.
    """
    rule = ctx.rule

    # Check if this is a supported rule kind
    is_lib = rule.kind in _SUPPORTED_LIB_KINDS
    is_bin = rule.kind in _SUPPORTED_BIN_KINDS
    if not (is_lib or is_bin):
        return []

    manifest = ctx.actions.declare_file("{}/Cargo.toml".format(_output_dir(ctx)))

    # Filter to only deps that have CargoManifestInfo (generated by this aspect)
    manifest_deps = [dep for dep in rule.attr.deps if CargoManifestInfo in dep]

    # rust_library exposes a CrateInfo directly. rust_shared_library and
    # rust_static_library wrap it in a TestCrateInfo instead. Use whichever is
    # available so the synthesized manifest's crate root matches the sources
    # the cbindgen rule feeds in (both come from this crate info).
    if CrateInfo in target:
        crate_info = target[CrateInfo]
    elif TestCrateInfo in target:
        crate_info = target[TestCrateInfo].crate
    else:
        crate_info = None

    if crate_info:
        crate_srcs = crate_info.srcs.to_list()
        root_src = crate_info.root
    else:
        crate_srcs = []
        for src in rule.attr.srcs:
            crate_srcs.extend(src.files.to_list())
        root_src = _find_crate_root_from_srcs(crate_srcs)

    if not root_src:
        fail("Could not find crate root (lib.rs or main.rs) in srcs for {}".format(target.label))

    # External sources are copied to a predictable location within the output
    # directory so the generated manifests can refer to them via relative
    # paths. Local sources are forwarded as is so cbindgen can parse the
    # sources of local dependency crates.
    if _is_external_crate(target):
        srcs, root_src = _clone_external_sources(ctx, crate_srcs, root_src)
        if not root_src:
            fail("Could not find crate root (lib.rs or main.rs) in srcs for {}".format(target.label))
    else:
        srcs = crate_srcs

    # Get edition - from crate info if available, otherwise use the rule
    # attribute or the default of the current rust toolchain.
    if crate_info and crate_info.edition:
        edition = crate_info.edition
    elif getattr(rule.attr, "edition", None):
        edition = rule.attr.edition
    else:
        edition = ctx.toolchains[Label("@rules_rust//rust:toolchain_type")].default_edition

    # Determine the crate type for the Cargo.toml
    if rule.kind == "rust_shared_library":
        crate_type_section = "[lib]\ncrate-type = [\"cdylib\"]"
    elif rule.kind == "rust_static_library":
        crate_type_section = "[lib]\ncrate-type = [\"staticlib\"]"
    elif rule.kind == "rust_library":
        crate_type_section = "[lib]"
    else:
        crate_type_section = "[[bin]]"

    ctx.actions.write(
        output = manifest,
        content = _CARGO_MANIFEST_TEMPLATE.format(
            target_label = target.label,
            build_file_path = ctx.build_file_path,
            crate_type = crate_type_section,
            name = target.label.name,
            # Cargo allows hyphens in package names but not in lib/bin target
            # names. Use the actual crate name when available, otherwise
            # sanitize the label name.
            lib_name = crate_info.name if crate_info else target.label.name.replace("-", "_"),
            version = getattr(rule.attr, "version", None) or "0.0.0",
            edition = edition,
            path = _relativize(root_src.path, manifest.dirname),
            dependencies = "\n".join([
                "{} = {{ path = \"{}\" }}".format(
                    dep.label.name,
                    _relativize(
                        dep[CargoManifestInfo].toml.dirname,
                        manifest.dirname,
                    ),
                )
                for dep in manifest_deps
            ]),
        ),
    )

    deps = [dep[OutputGroupInfo].all_files for dep in manifest_deps if OutputGroupInfo in dep]

    return [
        CargoManifestInfo(
            toml = manifest,
            deps = depset(transitive = deps),
        ),
        OutputGroupInfo(
            all_files = depset([manifest], transitive = deps + [depset(srcs)]),
        ),
    ]

cargo_manifest_aspect = aspect(
    doc = "An aspect that generates Cargo metadata (`Cargo.toml` files) for `rust_binary` and `rust_library` targets.",
    attr_aspects = ["deps"],
    implementation = _cargo_manifest_aspect_impl,
    toolchains = [config_common.toolchain_type("@rules_rust//rust:toolchain_type")],
)
