[package]
name = "wasm-ui"
version = "0.1.0"
edition = "2021"
description = "From template for starting a Yew project using Trunk"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["yew", "trunk", "bazel"]
categories = ["gui", "wasm", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = { version = "0.20", features = ["csr"] }
