[package]
name = "cargo_local"
version = "0.1.0"
authors = ["UebelAndre <github@uebelandre.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
zstd-sys = "=2.0.7+zstd.1.5.4"

[dev-dependencies]
tempfile = "3.2.0"
tokio-test = "0.4.2"
