package(default_visibility = ["//visibility:public"])
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_binary")

rust_binary(
  name = "hello_rustc_private",
  srcs = ["main.rs"],
  edition = "2018",
)
