[package]
name = "crate-types"
version = "0.1.0"
edition = "2018"

# Required to satisfy cargo but no `lib.rs` is expected to
# exist within test data.
[lib]
path = "lib.rs"

[dependencies]
clap = { version = "=4.1.1", default-features = false }
