package(default_visibility = ["//visibility:public"])

constraint_value(
    name = "unknown",
    constraint_setting = "@platforms//os",
)

constraint_value(
    name = "wasi",
    constraint_setting = "@platforms//os",
)
