load(":interleaved_dep_info_test.bzl", "interleaved_dep_info_test_suite")

############################ UNIT TESTS #############################
interleaved_dep_info_test_suite(name = "interleaved_dep_info_test_suite")
