fixedReleaser:
  login: scentini
  email: 11149636+scentini@users.noreply.github.com
moduleRoots:
  - "."
  - "extensions/bindgen"
  - "extensions/mdbook"
  - "extensions/prost"
  - "extensions/protobuf"
  - "extensions/pyo3"
  - "extensions/wasm_bindgen"
